INSERT INTO movies (
    title,
    description,
    duration_minutes,
    language,
    director,
    cast_members,
    poster_url,
    banner_url,
    trailer_url,
    release_date,
    age_rating,
    status
) VALUES
      (
          'The Conjuring',
          'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.',
          112,
          'English',
          'James Wan',
          'Vera Farmiga, Patrick Wilson, Lili Taylor, Ron Livingston, Mackenzie Foy',
          'https://image.tmdb.org/t/p/original/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
          'https://example.com/banners/TheConjuring.jpg',
          'https://www.youtube.com/watch?v=k10ETZ41q5o&t=2s',
          '2013-07-19',
          'R',
          'NOW_SHOWING'
      ),
      (
          'Dune: Part Two',
          'Paul Atreides unites with Chani and the Fremen while seeking revenge against those who destroyed his family.',
          166,
          'English',
          'Denis Villeneuve',
          'Timothee Chalamet, Zendaya, Rebecca Ferguson',
          'https://example.com/posters/dune2.jpg',
          'https://example.com/banners/dune2.jpg',
          'https://example.com/trailers/dune2',
          '2024-03-01',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'The Batman',
          'Batman ventures into Gotham''s underworld when a sadistic killer leaves behind a trail of cryptic clues.',
          176,
          'English',
          'Matt Reeves',
          'Robert Pattinson, Zoe Kravitz, Paul Dano',
          'https://example.com/posters/thebatman.jpg',
          'https://example.com/banners/thebatman.jpg',
          'https://example.com/trailers/thebatman',
          '2022-03-04',
          'R',
          'ENDED'
      ),
      (
          'Interstellar',
          'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
          169,
          'English',
          'Christopher Nolan',
          'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
          'https://example.com/posters/interstellar.jpg',
          'https://example.com/banners/interstellar.jpg',
          'https://example.com/trailers/interstellar',
          '2014-11-07',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'Avengers: Endgame',
          'The Avengers assemble once more to reverse Thanos'' actions and restore balance to the universe.',
          181,
          'English',
          'Anthony Russo, Joe Russo',
          'Robert Downey Jr., Chris Evans, Scarlett Johansson',
          'https://example.com/posters/endgame.jpg',
          'https://example.com/banners/endgame.jpg',
          'https://example.com/trailers/endgame',
          '2019-04-26',
          'PG',
          'ENDED'
      ),
      (
          'Inception',
          'A thief who steals corporate secrets through dream-sharing technology is given an inverse task of planting an idea.',
          148,
          'English',
          'Christopher Nolan',
          'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
          'https://example.com/posters/inception.jpg',
          'https://example.com/banners/inception.jpg',
          'https://example.com/trailers/inception',
          '2010-07-16',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'Spider-Man: No Way Home',
          'Spider-Man seeks Doctor Strange''s help when his identity is revealed, unleashing dangerous multiverse threats.',
          148,
          'English',
          'Jon Watts',
          'Tom Holland, Zendaya, Benedict Cumberbatch',
          'https://example.com/posters/nowayhome.jpg',
          'https://example.com/banners/nowayhome.jpg',
          'https://example.com/trailers/nowayhome',
          '2021-12-17',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'Oppenheimer',
          'The story of J. Robert Oppenheimer and the creation of the atomic bomb during World War II.',
          180,
          'English',
          'Christopher Nolan',
          'Cillian Murphy, Emily Blunt, Matt Damon',
          'https://example.com/posters/oppenheimer.jpg',
          'https://example.com/banners/oppenheimer.jpg',
          'https://example.com/trailers/oppenheimer',
          '2023-07-21',
          'R',
          'NOW_SHOWING'
      ),
      (
          'Top Gun: Maverick',
          'After more than thirty years of service, Maverick is called upon to train a new generation of elite pilots.',
          131,
          'English',
          'Joseph Kosinski',
          'Tom Cruise, Miles Teller, Jennifer Connelly',
          'https://example.com/posters/topgunmaverick.jpg',
          'https://example.com/banners/topgunmaverick.jpg',
          'https://example.com/trailers/topgunmaverick',
          '2022-05-27',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'Parasite',
          'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
          132,
          'Korean',
          'Bong Joon Ho',
          'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
          'https://example.com/posters/parasite.jpg',
          'https://example.com/banners/parasite.jpg',
          'https://example.com/trailers/parasite',
          '2019-05-30',
          'R',
          'ENDED'
      ),
      (
          'Joker',
          'A failed comedian descends into madness and sparks chaos in Gotham City.',
          122,
          'English',
          'Todd Phillips',
          'Joaquin Phoenix, Robert De Niro, Zazie Beetz',
          'https://example.com/posters/joker.jpg',
          'https://example.com/banners/joker.jpg',
          'https://example.com/trailers/joker',
          '2019-10-04',
          'R',
          'ENDED'
      ),
      (
          'Frozen II',
          'Anna, Elsa, Kristoff, Olaf and Sven leave Arendelle to travel to an ancient forest and discover Elsa''s true origin.',
          103,
          'English',
          'Chris Buck, Jennifer Lee',
          'Idina Menzel, Kristen Bell, Josh Gad',
          'https://example.com/posters/frozen2.jpg',
          'https://example.com/banners/frozen2.jpg',
          'https://example.com/trailers/frozen2',
          '2019-11-22',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'The Super Mario Bros. Movie',
          'Mario and Luigi are transported into a magical world and must help save it from Bowser.',
          92,
          'English',
          'Aaron Horvath, Michael Jelenic',
          'Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black',
          'https://example.com/posters/mario.jpg',
          'https://example.com/banners/mario.jpg',
          'https://example.com/trailers/mario',
          '2023-04-05',
          'PG',
          'NOW_SHOWING'
      );