INSERT INTO movies (
    title,
    description,
    duration_minutes,
    language,
    director,
    cast_members,
    poster_url,
    banner_url,
    trailer_url,
    release_date,
    age_rating,
    status
) VALUES
      -- ENDED
      (
          'Doraemon the Movie: Nobita''s Earth Symphony',
          'Doraemon and Nobita set out on a musical adventure to save the world from a crisis where music itself is in danger.',
          115,
          'Japanese',
          'Kazuaki Imai',
          'Wasabi Mizuta, Megumi Ohara, Yumi Kakazu, Subaru Kimura',
          'https://image.tmdb.org/t/p/original/1W5Kg4K27U3dx9Kxb8DaE6WFLHI.jpg',
          'https://example.com/banners/doraemon-earth-symphony.jpg',
          'https://www.youtube.com/watch?v=Bpf0r-nSyjU',
          '2024-03-01',
          'G',
          'ENDED'
      ),
      (
          'Spirited Away',
          'A young girl trapped in a mysterious spirit world must find the courage to save her parents and return home.',
          125,
          'Japanese',
          'Hayao Miyazaki',
          'Rumi Hiiragi, Miyu Irino, Mari Natsuki, Bunta Sugawara',
          'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
          'https://example.com/banners/spirited-away.jpg',
          'https://www.youtube.com/watch?v=ByXuk9QqQkk',
          '2001-07-20',
          'PG',
          'ENDED'
      ),
      (
          'Inside Out',
          'The emotions inside Riley''s mind struggle to guide her through a major life change.',
          95,
          'English',
          'Pete Docter',
          'Amy Poehler, Phyllis Smith, Richard Kind, Bill Hader',
          'https://image.tmdb.org/t/p/original/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
          'https://example.com/banners/inside-out.jpg',
          'https://www.youtube.com/watch?v=yRUAzGQ3nSY',
          '2015-06-19',
          'PG',
          'ENDED'
      ),
      (
          'Inside Out 2',
          'Riley''s emotional world gets more complicated when new emotions arrive at headquarters.',
          96,
          'English',
          'Kelsey Mann',
          'Amy Poehler, Maya Hawke, Kensington Tallman, Liza Lapira',
          'https://image.tmdb.org/t/p/original/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
          'https://example.com/banners/inside-out-2.jpg',
          'https://www.youtube.com/watch?v=LEjhY15eCx0',
          '2024-06-14',
          'PG',
          'ENDED'
      ),
      (
          'Despicable Me',
          'A supervillain''s life changes when three orphan girls unexpectedly melt his heart.',
          95,
          'English',
          'Pierre Coffin, Chris Renaud',
          'Steve Carell, Jason Segel, Russell Brand, Miranda Cosgrove',
          'https://image.tmdb.org/t/p/original/xIXhIlZDRmSSfNbpN7kBCm5hg39.jpg',
          'https://example.com/banners/despicable-me.jpg',
          'https://www.youtube.com/watch?v=zzCZ1W_CUoI',
          '2010-07-09',
          'PG',
          'ENDED'
      ),
      (
          'The Lion King',
          'A young lion prince must reclaim his place in the Circle of Life after tragedy and exile.',
          88,
          'English',
          'Roger Allers, Rob Minkoff',
          'Matthew Broderick, Jeremy Irons, James Earl Jones, Moira Kelly',
          'https://image.tmdb.org/t/p/original/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
          'https://example.com/banners/the-lion-king-1994.jpg',
          'https://www.youtube.com/watch?v=lFzVJEksoDY',
          '1994-06-24',
          'G',
          'ENDED'
      ),
      (
          'Beauty and the Beast',
          'Belle discovers the kindness hidden beneath the curse of a fearsome beast.',
          84,
          'English',
          'Gary Trousdale, Kirk Wise',
          'Paige O''Hara, Robby Benson, Jerry Orbach, Angela Lansbury',
          'https://image.tmdb.org/t/p/original/hUJ0UvQ5tgE2Z9WpfuduVSdiCiU.jpg',
          'https://example.com/banners/beauty-and-the-beast-1991.jpg',
          'https://www.youtube.com/watch?v=ig1P3s-qiT8',
          '1991-11-22',
          'G',
          'ENDED'
      ),
      (
          'Zootopia',
          'A rookie rabbit cop and a sly fox uncover a conspiracy in a city where animals live like humans.',
          108,
          'English',
          'Byron Howard, Rich Moore, Jared Bush',
          'Ginnifer Goodwin, Jason Bateman, Idris Elba, Jenny Slate',
          'https://image.tmdb.org/t/p/original/9LRFNLthb0jfWC0HUDUWjYgpP9F.jpg',
          'https://example.com/banners/zootopia.jpg',
          'https://www.youtube.com/watch?v=zMvrGUb2J68',
          '2016-03-04',
          'PG',
          'ENDED'
      ),
      (
          'Aladdin',
          'A street thief finds a magic lamp and is swept into a life-changing adventure.',
          90,
          'English',
          'Ron Clements, John Musker',
          'Scott Weinger, Robin Williams, Linda Larkin, Jonathan Freeman',
          'https://image.tmdb.org/t/p/original/oakAd8syy7jNQ4ZoaAGCQkTqcOV.jpg',
          'https://example.com/banners/aladdin-1992.jpg',
          'https://www.youtube.com/watch?v=eTjHiQKJUDY',
          '1992-11-25',
          'G',
          'ENDED'
      ),
      (
          'Sing',
          'A koala theater owner launches a singing competition to save his struggling theater.',
          108,
          'English',
          'Garth Jennings',
          'Matthew McConaughey, Reese Witherspoon, Scarlett Johansson, Taron Egerton',
          'https://image.tmdb.org/t/p/original/rwopfpHqPCYBSgBuZwkaXXqHp14.jpg',
          'https://example.com/banners/sing.jpg',
          'https://www.youtube.com/watch?v=9qPgK_u4vX8',
          '2016-12-21',
          'PG',
          'ENDED'
      ),
      (
          'Sing 2',
          'Buster Moon and his performers aim for a bigger stage in the entertainment capital.',
          110,
          'English',
          'Garth Jennings',
          'Matthew McConaughey, Reese Witherspoon, Scarlett Johansson, Taron Egerton',
          'https://image.tmdb.org/t/p/original/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg',
          'https://example.com/banners/sing-2.jpg',
          'https://www.youtube.com/watch?v=EPZu5MA2uqI',
          '2021-12-22',
          'PG',
          'ENDED'
      ),
      (
          'Up',
          'An elderly widower and an eager young scout set off on an unforgettable flying-house adventure.',
          96,
          'English',
          'Pete Docter, Bob Peterson',
          'Ed Asner, Christopher Plummer, Jordan Nagai, Bob Peterson',
          'https://image.tmdb.org/t/p/original/jX6cvQtuHTejs9HZ7IDEgKV3KDr.jpg',
          'https://example.com/banners/up.jpg',
          'https://www.youtube.com/watch?v=HWEW_qTLSEE',
          '2009-05-29',
          'PG',
          'ENDED'
      ),
      (
          'The Princess and the Frog',
          'A hardworking waitress and a prince under a curse search for a way to become human again.',
          97,
          'English',
          'Ron Clements, John Musker',
          'Anika Noni Rose, Bruno Campos, Keith David, Oprah Winfrey',
          'https://image.tmdb.org/t/p/original/v6nAUs62OJ4DXmnnmPFeVmMz8H9.jpg',
          'https://example.com/banners/the-princess-and-the-frog.jpg',
          'https://www.youtube.com/watch?v=uQBy6jqbmlU',
          '2009-12-11',
          'G',
          'ENDED'
      ),
      (
          'The Little Mermaid',
          'A curious mermaid dreams of life on land and makes a dangerous bargain to pursue it.',
          83,
          'English',
          'Ron Clements, John Musker',
          'Jodi Benson, Samuel E. Wright, Rene Auberjonois, Pat Carroll',
          'https://image.tmdb.org/t/p/original/plcZXvI310FkbwIptvd6rqk63LP.jpg',
          'https://example.com/banners/the-little-mermaid-1989.jpg',
          'https://www.youtube.com/watch?v=ur1B_f1FXZ4',
          '1989-11-17',
          'G',
          'ENDED'
      ),
      (
          'Tangled',
          'Rapunzel leaves her tower with a wanted thief and discovers the truth about her past.',
          100,
          'English',
          'Nathan Greno, Byron Howard',
          'Mandy Moore, Zachary Levi, Donna Murphy, Ron Perlman',
          'https://image.tmdb.org/t/p/original/ym7Kst6a4uodryxqbGOxmewF235.jpg',
          'https://example.com/banners/tangled.jpg',
          'https://www.youtube.com/watch?v=ycoY201RTRo',
          '2010-11-24',
          'PG',
          'ENDED'
      ),
      (
          'The Conjuring',
          'Paranormal investigators Ed and Lorraine Warren help a family terrorized by a dark presence.',
          112,
          'English',
          'James Wan',
          'Vera Farmiga, Patrick Wilson, Lili Taylor, Ron Livingston',
          'https://image.tmdb.org/t/p/original/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
          'https://example.com/banners/the-conjuring.jpg',
          'https://www.youtube.com/watch?v=k10ETZ41q5o&t=2s',
          '2013-07-19',
          'R',
          'ENDED'
      ),
      (
          'The Conjuring 2',
          'The Warrens travel to England to investigate another terrifying case involving a possessed child.',
          134,
          'English',
          'James Wan',
          'Vera Farmiga, Patrick Wilson, Madison Wolfe, Frances O''Connor',
          'https://image.tmdb.org/t/p/original/zEqyD0SBt6HL7W9JQoWwtd5Do1T.jpg',
          'https://example.com/banners/the-conjuring-2.jpg',
          'https://www.youtube.com/watch?v=VFsmuRPClr4',
          '2016-06-10',
          'R',
          'ENDED'
      ),
      (
          'The Nun',
          'A priest and a novice uncover a demonic secret at a remote abbey in Romania.',
          96,
          'English',
          'Corin Hardy',
          'Demián Bichir, Taissa Farmiga, Jonas Bloquet, Bonnie Aarons',
          'https://image.tmdb.org/t/p/original/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg',
          'https://example.com/banners/the-nun.jpg',
          'https://www.youtube.com/watch?v=pzD9zGcUNrw',
          '2018-09-07',
          'R',
          'ENDED'
      ),
      (
          'The Nun II',
          'Sister Irene must confront the evil force Valak once again after another brutal supernatural attack.',
          110,
          'English',
          'Michael Chaves',
          'Taissa Farmiga, Jonas Bloquet, Storm Reid, Anna Popplewell',
          'https://image.tmdb.org/t/p/original/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg',
          'https://example.com/banners/the-nun-2.jpg',
          'https://www.youtube.com/watch?v=QF-oyCwaArU',
          '2023-09-08',
          'R',
          'ENDED'
      ),
      (
          'Avengers: Age of Ultron',
          'The Avengers face a dangerous artificial intelligence that threatens humanity.',
          141,
          'English',
          'Joss Whedon',
          'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
          'https://image.tmdb.org/t/p/original/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
          'https://example.com/banners/avengers-age-of-ultron.jpg',
          'https://www.youtube.com/watch?v=tmeOjFno6Do',
          '2015-05-01',
          'PG',
          'ENDED'
      ),
      (
          'Avengers: Endgame',
          'The surviving Avengers make one final stand to undo Thanos'' devastation.',
          181,
          'English',
          'Anthony Russo, Joe Russo',
          'Robert Downey Jr., Chris Evans, Scarlett Johansson, Mark Ruffalo',
          'https://image.tmdb.org/t/p/original/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
          'https://example.com/banners/avengers-endgame.jpg',
          'https://www.youtube.com/watch?v=TcMBFSGVi1c',
          '2019-04-26',
          'PG',
          'ENDED'
      ),
      (
          'Iron Man',
          'Tony Stark becomes a high-tech hero after surviving a life-changing attack.',
          126,
          'English',
          'Jon Favreau',
          'Robert Downey Jr., Gwyneth Paltrow, Terrence Howard, Jeff Bridges',
          'https://image.tmdb.org/t/p/original/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
          'https://example.com/banners/iron-man.jpg',
          'https://www.youtube.com/watch?v=8ugaeA-nMTc',
          '2008-05-02',
          'PG',
          'ENDED'
      ),
      (
          'Iron Man 2',
          'Tony Stark faces government pressure, corporate rivalry, and a new enemy.',
          124,
          'English',
          'Jon Favreau',
          'Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson',
          'https://image.tmdb.org/t/p/original/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
          'https://example.com/banners/iron-man-2.jpg',
          'https://www.youtube.com/watch?v=BoohRoVA9WQ',
          '2010-05-07',
          'PG',
          'ENDED'
      ),
      (
          'Iron Man 3',
          'Tony Stark is pushed to his limits when a mysterious enemy destroys his world.',
          130,
          'English',
          'Shane Black',
          'Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Guy Pearce',
          'https://image.tmdb.org/t/p/original/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
          'https://example.com/banners/iron-man-3.jpg',
          'https://www.youtube.com/watch?v=f_h95mEd4TI',
          '2013-05-03',
          'PG',
          'ENDED'
      ),
      (
          'Captain America: The First Avenger',
          'Steve Rogers becomes Captain America and fights Hydra during World War II.',
          124,
          'English',
          'Joe Johnston',
          'Chris Evans, Hayley Atwell, Sebastian Stan, Hugo Weaving',
          'https://image.tmdb.org/t/p/original/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
          'https://example.com/banners/captain-america-the-first-avenger.jpg',
          'https://www.youtube.com/watch?v=JerVrbLldXw',
          '2011-07-22',
          'PG',
          'ENDED'
      ),
      (
          'Thor',
          'The arrogant god of thunder is cast to Earth and learns what it means to be worthy.',
          115,
          'English',
          'Kenneth Branagh',
          'Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins',
          'https://image.tmdb.org/t/p/original/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
          'https://example.com/banners/thor-2011.jpg',
          'https://www.youtube.com/watch?v=JOddp-nlNvQ',
          '2011-05-06',
          'PG',
          'ENDED'
      ),
      (
          'The Avengers',
          'Earth''s mightiest heroes unite to stop Loki and an invading alien force.',
          143,
          'English',
          'Joss Whedon',
          'Robert Downey Jr., Chris Evans, Scarlett Johansson, Chris Hemsworth',
          'https://image.tmdb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
          'https://example.com/banners/the-avengers-2012.jpg',
          'https://www.youtube.com/watch?v=eOrNdBpGMv8',
          '2012-05-04',
          'PG',
          'ENDED'
      ),
      (
          'Avengers: Infinity War',
          'The Avengers and their allies battle Thanos as he races to collect all six Infinity Stones.',
          149,
          'English',
          'Anthony Russo, Joe Russo',
          'Robert Downey Jr., Chris Hemsworth, Josh Brolin, Chris Evans',
          'https://image.tmdb.org/t/p/original/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
          'https://example.com/banners/avengers-infinity-war.jpg',
          'https://www.youtube.com/watch?v=QwievZ1Tx-8',
          '2018-04-27',
          'PG',
          'ENDED'
      ),

      -- NOW SHOWING
      (
          'Michael',
          'A biographical drama following the life and legacy of Michael Jackson.',
          127,
          'English',
          'Antoine Fuqua',
          'Jaafar Jackson, Nia Long, Colman Domingo, Miles Teller',
          'https://image.tmdb.org/t/p/original/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg',
          'https://example.com/banners/michael-2026.jpg',
          'https://www.youtube.com/watch?v=3zOLzsbOleM',
          '2026-04-24',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'The Super Mario Galaxy Movie',
          'Mario and his friends head into a cosmic adventure filled with new worlds and bigger threats.',
          98,
          'English',
          'Aaron Horvath, Michael Jelenic',
          'Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black',
          'https://image.tmdb.org/t/p/original/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
          'https://example.com/banners/the-super-mario-galaxy-movie.jpg',
          'https://www.youtube.com/watch?v=En5QZmL5R1s',
          '2026-04-01',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'Phí Phông: Quỷ Máu Rừng Thiêng',
          'Two apprentice shamans venture into the mountains to stop a blood demon linked to a terrifying local curse.',
          120,
          'Vietnamese',
          'Đỗ Quốc Trung',
          'Kiều Minh Tuấn, Nina Nutthacha Padovan, Diệp Bảo Ngọc, Đoàn Minh Anh',
          'https://image.tmdb.org/t/p/original/1c5XWuA9ETEUZcMAF1ngk0kBNEh.jpg',
          'https://example.com/banners/phi-phong-quy-mau-rung-thieng.jpg',
          'https://www.youtube.com/watch?v=AFkKZXbzHdI',
          '2026-04-24',
          'R',
          'NOW_SHOWING'
      ),
      (
          'Lupin the IIIrd: The Movie - The Immortal Bloodline',
          'Lupin and his crew pursue treasure on a deadly island ruled by a mysterious immortal enemy.',
          93,
          'Japanese',
          'Takeshi Koike',
          'Kanichi Kurita, Akio Otsuka, Daisuke Namikawa, Miyuki Sawashiro',
          'https://image.tmdb.org/t/p/original/oAxA9yZDFbwi4OH5TurfWZxRj2A.jpg',
          'https://example.com/banners/lupin-the-iiird-the-movie-the-immortal-bloodline.jpg',
          'https://www.youtube.com/watch?v=f3vu4JydRRA',
          '2025-06-27',
          'PG',
          'NOW_SHOWING'
      ),
      (
          'Lee Cronin''s The Mummy',
          'A family is reunited with their long-missing daughter, only to realize an ancient evil has come back with her.',
          134,
          'English',
          'Lee Cronin',
          'Jack Reynor, Laia Costa, May Calamawy, Natalie Grace',
          'https://image.tmdb.org/t/p/original/8L8efNkz8rUmwR7sV0g3vnC9yjn.jpg',
          'https://example.com/banners/lee-cronins-the-mummy.jpg',
          'https://www.youtube.com/watch?v=XJ0uv-phsDk',
          '2026-04-17',
          'R',
          'NOW_SHOWING'
      ),
      (
          'Ready or Not 2: Here I Come',
          'Grace is pulled into another deadly game after surviving the events of the first film.',
          108,
          'English',
          'Matt Bettinelli-Olpin, Tyler Gillett',
          'Samara Weaving, Kathryn Newton, Sarah Michelle Gellar, Elijah Wood',
          'https://image.tmdb.org/t/p/original/jRf89HVEtBZiSnOXXWDhZOfuTwW.jpg',
          'https://example.com/banners/ready-or-not-2-here-i-come.jpg',
          'https://www.youtube.com/watch?v=7K3sNRm8J0w',
          '2026-03-20',
          'R',
          'NOW_SHOWING'
      ),

      -- COMING SOON
      (
          'The Legend of Aang: The Last Airbender',
          'Aang and his friends face a new threat as they fight to protect their world and culture.',
          99,
          'English',
          'Steve Ahn, William Mata',
          'Eric Nam, Jessica Matten, Román Zaragoza, Dionne Quan',
          'https://image.tmdb.org/t/p/original/29Jdsak3SrwGds5k1t43kH6Khed.jpg',
          'https://example.com/banners/the-legend-of-aang-the-last-airbender.jpg',
          'https://www.youtube.com/watch?v=KA_YIcMqsAs',
          '2026-10-09',
          'PG',
          'COMING_SOON'
      ),
      (
          'Spider-Man: Brand New Day',
          'Peter Parker begins a new chapter of his life while facing fresh threats in New York.',
          140,
          'English',
          'Destin Daniel Cretton',
          'Tom Holland, Zendaya, Sadie Sink, Jacob Batalon',
          'https://image.tmdb.org/t/p/original/pspkSVP39NGa6G2rvK5KlMjvYUe.jpg',
          'https://example.com/banners/spider-man-brand-new-day.jpg',
          'https://www.youtube.com/watch?v=8TZMtslA3UY',
          '2026-07-31',
          'PG',
          'COMING_SOON'
      ),
      (
          'Avengers: Doomsday',
          'The Avengers face a multiversal threat led by Doctor Doom.',
          185,
          'English',
          'Anthony Russo, Joe Russo',
          'Robert Downey Jr., Pedro Pascal, Chris Hemsworth, Vanessa Kirby',
          'https://image.tmdb.org/t/p/original/8HkIe2i4ScpCkcX9SzZ9IPasqWV.jpg',
          'https://example.com/banners/avengers-doomsday.jpg',
          'https://www.youtube.com/watch?v=Z5eaSV-Klic',
          '2026-12-18',
          'PG',
          'COMING_SOON'
      ),
      (
          'Dune: Part Three',
          'Paul Atreides faces the consequences of power as the story of Dune continues.',
          180,
          'English',
          'Denis Villeneuve',
          'Timothée Chalamet, Zendaya, Rebecca Ferguson, Anya Taylor-Joy',
          'https://image.tmdb.org/t/p/original/b4wekkUaxExzOeGe7hKXzhnyXHt.jpg',
          'https://example.com/banners/dune-part-three.jpg',
          'https://www.youtube.com/watch?v=3_9vCamtuPY',
          '2026-12-18',
          'PG',
          'COMING_SOON'
      ),
      (
          'Sonic the Hedgehog 4',
          'Sonic and his friends return for another high-speed battle against a new threat.',
          110,
          'English',
          'Jeff Fowler',
          'Keanu Reeves, James Marsden, Nick Offerman, Jim Carrey',
          'https://image.tmdb.org/t/p/original/t8uoHBODkFlSQJRL6qc4IclUBlH.jpg',
          'https://example.com/banners/sonic-the-hedgehog-4.jpg',
          'https://www.youtube.com/watch?v=YShjCIA9aXk',
          '2027-03-19',
          'PG',
          'COMING_SOON'
      ),
      (
          'Spider-Noir',
          'An aging private investigator in 1930s New York is forced to confront his past as a masked hero.',
          45,
          'English',
          'Harry Bradbeer',
          'Nicolas Cage, Brendan Gleeson, Lamorne Morris, Abraham Popoola',
          'https://image.tmdb.org/t/p/original/cRAzL6mmdM6Q6UuQgc335UMgcfd.jpg',
          'https://example.com/banners/spider-noir.jpg',
          'https://www.youtube.com/watch?v=b-Blr0_koQA',
          '2026-05-27',
          'PG',
          'COMING_SOON'
      );