server:
  port: ${SERVER_PORT:8080}

app:
  seat-hold:
    duration-minutes: ${SEAT_HOLD_DURATION_MINUTES:10}
    cleanup-fixed-delay-ms: ${SEAT_HOLD_CLEANUP_FIXED_DELAY_MS:30000}

  cors:
    allowed-origins:
      - ${FRONTEND_URL:http://localhost:5173}

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}
    issuer: ${JWT_ISSUER:movie-booking-server}

spring:
  config:
    import: "optional:file:../.env[.properties]"

  application:
    name: ${APP_NAME:movie-booking-server}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}

  flyway:
    enabled: true

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.flywaydb: INFO